const Productdetail = [
  {
    id: 1,
    Title: "T-Shirt",
    Cat: "Men",
    Price: "50",
    Img: "./img/men/2.jpeg",
  },
  {
    id: 2,
    Title: "Stripe T-Shirt",
    Cat: "Men",
    Price: "168",
    Img: "./img/men/8.jpeg",
  },
  {
    id: 3,
    Title: "Women shorts",
    Cat: "Women",
    Price: "899",
    Img: "./img/women/31.jpeg",
  },
  {
    id: 4,
    Title: "Traditional Kurti",
    Cat: "Women",
    Price: "49",
    Img: "./img/women/15.jpg",
  },
  {
    id: 5,
    Title: "Unique Design Saree",
    Cat: "Women",
    Price: "49",
    Img: "./img/women/8.jpeg",
  },
  {
    id: 6,
    Title: "Amazing Designer Dress",
    Cat: "Women",
    Price: "156",
    Img: "./img/women/57.jpeg",
  },
  {
    id: 7,
    Title: "Kid's Traditional Outfit",
    Cat: "Kid",
    Price: "2098",
    Img: "./img/kids/24.jpeg",
  },
  {
    id: 8,
    Title: "Awesome kid's Saree Design",
    Cat: "Kid",
    Price: "386",
    Img: "./img/kids/16.jpeg",
  },
  {
    id: 9,
    Title: "South Indian dresses",
    Cat: "Kid",
    Price: "693",
    Img: "./img/kids/34.jpg",
  },
  {
    id: 10,
    Title: "Stunning casual shoes",
    Cat: "Shoe",
    Price: "5036",
    Img: "./img/shoes/2.jpeg",
  },
  {
    id: 11,
    Title: "Top-Class Sneakers",
    Cat: "Shoe",
    Price: "198",
    Img: "./img/shoes/12.jpeg",
  },
  {
    id: 12,
    Title: "Beautiful women wears",
    Cat: "Shoe",
    Price: "795",
    Img: "./img/shoes/29.jpeg",
  },
  {
    id: 13,
    Title: "Nike black_green",
    Cat: "Shoe",
    Price: "2799",
    Img: "./img/shoes/60.jpeg",
  },
  {
    id: 14,
    Title: "Nike Air Jordan red_black",
    Cat: "Shoe",
    Price: "4799",
    Img: "./img/shoes/59.jpeg",
  },
  {
    id: 15,
    Title: "Blue sneakers kids",
    Cat: "Shoe",
    Price: "599",
    Img: "./img/shoes/58.jpeg",
  },
  {
    id: 16,
    Title: "Woodland men",
    Cat: "Shoe",
    Price: "3799",
    Img: "./img/shoes/55.jpeg",
  },
  {
    id: 17,
    Title: "Woodland women",
    Cat: "Shoe",
    Price: "2999",
    Img: "./img/shoes/54.jpeg",
  },
  {
    id: 18,
    Title: "Bold women high heels_thigh",
    Cat: "Shoe",
    Price: "1699",
    Img: "./img/shoes/51.webp",
  },
  {
    id: 19,
    Title: "Billabong slippers",
    Cat: "Shoe",
    Price: "349",
    Img: "./img/shoes/50.jpeg",
  },
  {
    id: 20,
    Title: "women flip flops",
    Cat: "Shoe",
    Price: "789",
    Img: "./img/shoes/39.jpeg",
  },
  {
    id: 21,
    Title: "Beautiful women black mavirs",
    Cat: "Shoe",
    Price: "1799",
    Img: "./img/shoes/35.jpeg",
  },
  {
    id: 22,
    Title: "Beautiful women wears",
    Cat: "Shoe",
    Price: "793",
    Img: "./img/shoes/29.jpeg",
  },
  {
    id: 23,
    Title: "men shinning loafers_black",
    Cat: "Shoe",
    Price: "1199",
    Img: "./img/shoes/4.jpeg",
  },
  {
    id: 24,
    Title: "men formals",
    Cat: "Shoe",
    Price: "1099",
    Img: "./img/shoes/5.jpeg",
  },
  {
    id: 25,
    Title: "men sherwani",
    Cat: "Men",
    Price: "2799",
    Img: "./img/men/12.jpeg",
  },
  {
    id: 26,
    Title: "men textured sherwani",
    Cat: "Men",
    Price: "2999",
    Img: "./img/men/21.jpeg",
  },
  {
    id: 27,
    Title: "girls beautiful white frock",
    Cat: "Kid",
    Price: "789",
    Img: "./img/kids/52.jpeg",
  },
  {
    id: 28,
    Title: "kids bermuda jeans",
    Cat: "Kid",
    Price: "899",
    Img: "./img/kids/50.jpeg",
  },
  {
    id: 29,
    Title: "kids black t-shirt",
    Cat: "Kid",
    Price: "699",
    Img: "./img/kids/39.jpeg",
  },
  {
    id: 30,
    Title: "women shirt_blonde",
    Cat: "Women",
    Price: "1199",
    Img: "./img/women/53.jpg",
  },
  {
    id: 31,
    Title: "women formal pant_blue",
    Cat: "Women",
    Price: "1000",
    Img: "./img/women/49.jpeg",
  },
  {
    id: 32,
    Title: "women formal pant_black",
    Cat: "Women",
    Price: "1000",
    Img: "./img/women/48.jpeg",
  },
  {
    id: 33,
    Title: "women joggers",
    Cat: "Women",
    Price: "599",
    Img: "./img/women/46.jpeg",
  },
  {
    id: 34,
    Title: "nike women joggers_black",
    Cat: "Women",
    Price: "1099",
    Img: "./img/women/44.jpeg",
  },
  {
    id: 35,
    Title: "women night suit_white",
    Cat: "Women",
    Price: "999",
    Img: "./img/women/39.jpeg",
  },
  {
    id: 36,
    Title: "women onepeice",
    Cat: "Women",
    Price: "1199",
    Img: "./img/women/35.jpeg",
  },
  {
    id: 37,
    Title: "women nighty",
    Cat: "Women",
    Price: "399",
    Img: "./img/women/34.jpeg",
  },
  {
    id: 38,
    Title: "women jeans",
    Cat: "Women",
    Price: "1299",
    Img: "./img/women/29.jpeg",
  },
  {
    id: 39,
    Title: "women punjabi suit",
    Cat: "Women",
    Price: "1149",
    Img: "./img/women/16.jpeg",
  },
  {
    id: 40,
    Title: "women stunning black kurti",
    Cat: "Women",
    Price: "1599",
    Img: "./img/women/18.jpeg",
  },
  {
    id: 41,
    Title: "girls dress_pink",
    Cat: "Kid",
    Price: "999",
    Img: "./img/kids/7.jpeg",
  },
  {
    id: 42,
    Title: "girls kurti_green",
    Cat: "Kid",
    Price: "1099",
    Img: "./img/women/18.jpeg",
  },
  {
    id: 43,
    Title: "women red textured saree",
    Cat: "Women",
    Price: "1799",
    Img: "./img/women/3.jpeg",
  },
];
export default Productdetail;
